name: Markdown Table of Contents

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Table of Contents
      uses: ghiculescu/actions-md-toc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: '/*.md' # Adjust file pattern as needed

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto-generate table of contents"
        git push